apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "papercups.fullname" . }}
  labels:
    {{- include "papercups.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "papercups.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "papercups.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "papercups.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: {{ .Values.image.command }}
          args: {{ .Values.image.args }}
          ports:
            - name: http
              containerPort: 4000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/ping
              port: http
            initialDelaySeconds: 20
            periodSeconds: 5
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /api/ping
              port: http
            initialDelaySeconds: 20
            periodSeconds: 3
            failureThreshold: 3
          terminationMessagePolicy: FallbackToLogsOnError
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if or ($.Values.configMap) ($.Values.secrets) }}
          env:
          {{- include "papercups.psql.envs" . | nindent 12 }}
          envFrom:
          {{- if $.Values.configMap }}
            - configMapRef:
                name: {{ template "papercups.fullname" $ }}
          {{- end }}
          {{- if or $.Values.secrets $.Values.global.postgresql }}
            - secretRef:
                name: {{ template "papercups.fullname" $ }}
          {{- end }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}