apiVersion: v1
kind: Secret
metadata:
  name: {{ template "papercups.fullname" . }}
  labels:
    {{- include "papercups.labels" . | nindent 4 }}
type: Opaque
data:
{{- $db_host := include "papercups.psql.host" . -}}
{{- $db_name := coalesce .databaseName .Values.global.postgresql.postgresqlDatabase "papercups" -}}
{{- $db_user := coalesce .Values.global.postgresql.postgresqlUsername "papercups" -}}
{{- $db_password := coalesce .Values.global.postgresql.postgresqlPassword "changeit" -}}
{{- $db_url := printf "ecto://%s:%s@%s.default.svc.cluster.local/%s" $db_user $db_password $db_host $db_name -}}
{{- if .Values.secrets }}
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ default "MISSING" $value | b64enc | quote }}
{{- end }}
{{- end }}
{{- if and .Values.global.postgresql (not .Values.secrets.DATABASE_URL) }}
#  DATABASE_URL_ASCII: {{ $db_url | quote }}
  DATABASE_URL: {{ $db_url | b64enc | quote }}
{{ end }}
