name: Lint and Test Charts

on:
  pull_request:
    paths:
      - "charts/**"

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run helm-docs
        run: .github/helm-docs.sh
      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.6.0
        with:
          commit_message: ":robot: update docs [skip ci]"
          repository: .

  changed:
    runs-on: ubuntu-latest
    outputs:
      charts: ${{ steps.list-changed.outputs.changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1
      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config .github/ct.yaml)
          if [[ -n "$changed" ]]; then
            echo -n "Charts changed:"
            echo "$changed"
            echo "::set-output name=changed::$changed"
          fi
      - name: Run chart-testing (lint)
        run: ct lint --config .github/ct.yaml

  kubeval-chart:
    runs-on: ubuntu-latest
    needs:
      - changed
    strategy:
      matrix:
        # When changing versions here, check that the version exists at: https://github.com/instrumenta/kubernetes-json-schema
        k8s:
          - v1.17.4
          - v1.18.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Add papercups helm repo
        run: helm repo add papercups-io https://papercups-io.github.io/charts && helm repo update
      - name: Run kubeval
        env:
          KUBERNETES_VERSION: ${{ matrix.k8s }}
          CHANGED_CHARTS: ${{needs.changed.outputs.charts}}
        run: .github/kubeval.sh

  install-chart:
    name: install-chart
    runs-on: ubuntu-latest
    needs:
      - kubeval-chart
    strategy:
      matrix:
        # When changing versions here, check that the version exists at: https://hub.docker.com/r/kindest/node/tags?page=1&ordering=last_updated
        k8s:
          - v1.16.15
          - v1.17.17
          - v1.18.15
          - v1.19.7
          - v1.20.2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Create kind ${{ matrix.k8s }} cluster
        uses: helm/kind-action@v1.0.0
        with:
          node_image: kindest/node:${{ matrix.k8s }}
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1
      - name: helm repo add bitnami
        run: helm repo add bitnami https://charts.bitnami.com/bitnami
      - name: Install postgresql dependency
        run: helm install papercups-db bitnami/postgresql --set postgresqlUsername=papercups,postgresqlPassword=changeit,postgresqlDatabase=papercups
      - name: Run chart-testing (install)
        run: ct install --config .github/ct.yaml

  pr-validated:
    name: pr-validated
    runs-on: ubuntu-latest
    needs:
      - install-chart
    steps:
      - name: validate
        run: echo "PR passed chart-testing install"